### ISSUE TITLE
songRoll-sky doesn't work on production mod

### ISSUE THREAD

**Issue by kuaikuaikim** [antidiestro/songroll-sky#4]
@ReneMoraales  I use meteor up to deploy songRoll-sky on production mod . It works fine on my locally but doesn't work on production mod. When i open the page and just show an iron router error. 

iron:router
Organize your Meteor application.
Router.route('/', function () {
  this.render('Home', {
    data: function () { return Items.findOne({_id: this.params._id}); }
  });
});

It seems like a iron router issue. Maybe the songRoll-sky iron router api are too old. I update meteor before.

**Comment by antidiestro** [comment]
@quickj sorry, that's probably it. I don't really have time to work on this project for now, last update to it was for Meteor 0.9.3.1.
